[workspace]
authors = ["Baptiste PIERRAT <pierrat@emse.fr>"]
channels = ["conda-forge"]
name = "tp-identification"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = ">=3.10"
fenics-dolfinx = "==0.9.0"
python-gmsh = "*"
matplotlib = "*"
scipy = "*"
jupyterlab = "*"
ipympl = ">=0.10.0,<0.11"
k3d = ">=2.17.0,<3"
notebook = ">=7.6.0,<8"

[pypi-dependencies]
scienceplots = ">=2.2.2, <3"


# --- Cluster Specific Configuration ---

# 1. Define a feature for the cluster
[feature.cluster]
platforms = [{ platform = "linux-64", glibc = "2.17" }]

# 2. Define the cluster environment that activates that feature
[environments]
cluster = ["cluster"]

